<?php

namespace DoctrineProxies\__CG__\App\Entities\Freelancer;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Freelancer extends \App\Entities\Freelancer\Freelancer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'uuid', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'rememberToken', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'email', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'password', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'hourRate', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'proposals', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'recordedEvents'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'uuid', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'rememberToken', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'email', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'password', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'hourRate', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'proposals', '' . "\0" . 'App\\Entities\\Freelancer\\Freelancer' . "\0" . 'recordedEvents'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Freelancer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getEmail(): \App\ValueObjects\Email
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): \App\ValueObjects\Password
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getHourRate(): \App\ValueObjects\Money
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHourRate', []);

        return parent::getHourRate();
    }

    /**
     * {@inheritDoc}
     */
    public function applyForJob(\App\Entities\Job\Job $job, \App\ValueObjects\EstimatedTime $estimatedTime, \App\ValueObjects\CoverLetter $coverLetter): \App\Entities\Proposal\Proposal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'applyForJob', [$job, $estimatedTime, $coverLetter]);

        return parent::applyForJob($job, $estimatedTime, $coverLetter);
    }

    /**
     * {@inheritDoc}
     */
    public function addProposal(\App\Entities\Proposal\Proposal $proposal): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProposal', [$proposal]);

        parent::addProposal($proposal);
    }

    /**
     * {@inheritDoc}
     */
    public function getProposals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProposals', []);

        return parent::getProposals();
    }

    /**
     * {@inheritDoc}
     */
    public function equalsTo(\App\Entities\Freelancer\Freelancer $other): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'equalsTo', [$other]);

        return parent::equalsTo($other);
    }

    /**
     * {@inheritDoc}
     */
    public function isAuthorOf(\App\Entities\Proposal\Proposal $proposal): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAuthorOf', [$proposal]);

        return parent::isAuthorOf($proposal);
    }

    /**
     * {@inheritDoc}
     */
    public function releaseEvents(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'releaseEvents', []);

        return parent::releaseEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthIdentifierName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthIdentifierName', []);

        return parent::getAuthIdentifierName();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthPassword', []);

        return parent::getAuthPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRememberTokenName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRememberTokenName', []);

        return parent::getRememberTokenName();
    }

    /**
     * {@inheritDoc}
     */
    public function getRememberToken(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRememberToken', []);

        return parent::getRememberToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setRememberToken($value): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRememberToken', [$value]);

        parent::setRememberToken($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthIdentifier', []);

        return parent::getAuthIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function can($abilities, $arguments = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'can', [$abilities, $arguments]);

        return parent::can($abilities, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function cant($abilities, $arguments = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cant', [$abilities, $arguments]);

        return parent::cant($abilities, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function cannot($abilities, $arguments = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cannot', [$abilities, $arguments]);

        return parent::cannot($abilities, $arguments);
    }

}
